runtime: nodejs20

env: standard

entrypoint: npm run start

handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /_next/webpack-hmr
    static_dir: .next/webpack-hmr
  - url: /.*
    script: auto
    secure: always  
